### ISSUE TITLE
Any luck deploying with Now?

### ISSUE THREAD

**Issue by gavinmcfarland** [DanWebb/jdown#18]
Hi, I'm hoping to use this with Zeit Now but I'm having trouble getting Now to read the markdown files.

When I use `jdown('content/posts/2019/09/').then(content => console.log(content));`

Content structure is as follows:

```
content/
  posts/
    2019/
       09/
         example-post.md
         another-example.md
```

In my application and run `now dev` I get the following error message

```bash
ncc: Module directory "/Users/limitlessloop/Repos/marko-webpack/node_modules/exec-buffer/node_modules/cross-spawn" attempted to require "spawn-sync" but could not be resolved, assuming external.
> Built @now/node-server:dist/server/main.js [13s]
(node:98095) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
Unhandled rejection: [Error: ENOENT: no such file or directory, scandir '/private/var/folders/qq/dhl743ln605cnnbb6zdf_qcc0000gn/T/zeit-fun-0ec4687f28702/content/posts/2019/09'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'scandir',
  path: '/private/var/folders/qq/dhl743ln605cnnbb6zdf_qcc0000gn/T/zeit-fun-0ec4687f28702/content/posts/2019/09'
}
LambdaError: RequestId: 0024e343-6ee6-4f6b-9f2a-a141120e6494 Process exited before completing request
    at Lambda.<anonymous> (/Users/limitlessloop/.nvm/versions/node/v12.4.0/lib/node_modules/now/dist/index.js:2:3268619)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/limitlessloop/.nvm/versions/node/v12.4.0/lib/node_modules/now/dist/index.js:2:3266490)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
> GET /service-worker.js
(node:98096) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
Unhandled rejection: [Error: ENOENT: no such file or directory, scandir '/private/var/folders/qq/dhl743ln605cnnbb6zdf_qcc0000gn/T/zeit-fun-0ec4687f28702/content/posts/2019/09'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'scandir',
  path: '/private/var/folders/qq/dhl743ln605cnnbb6zdf_qcc0000gn/T/zeit-fun-0ec4687f28702/content/posts/2019/09'
}
```

I know reading files with Now can behave oddly, but I'm not sure how jdown is reading the markdown files to be sure. I appreciate this is likely an issue with Now, but wondered if anything in the error output gives you any clues as to what the problem is?

The first thing I noticed is that it's looking for a directory and not a file `/private/var/folders/qq/dhl743ln605cnnbb6zdf_qcc0000gn/T/zeit-fun-0ec4687f28702/content/posts/2019/09`, so even by telling Now to manually include the content files, it's not finding them because it's looking for a directory.

**Comment by gavinmcfarland** [comment]
After playing around with it a bit more I was able to get it to work. I needed to both use an absolute path and include the files in the `now.json` configuration. It may be of use to someone else in the furture.

Using an absolute path

```js
jdown(process.cwd() + '/content/posts/2019/09/').then(content => console.log(content));
```

Configuration for Now needs to specify the folder for the markdown files using the `includeFiles` attribute. For example, mine looks like this...

```json
{
	"name": "personal-site",
	"version": 2,
	"builds": [{
		"src": "dist/server/main.js",
		"use": "@now/node-server",
		"config": {
			"includeFiles": [
				"../../content/**"
			]
		}
	}]
}
```

The `includeFiles` path is relative to the entry point of the `src` file. Something the Now documentation doesn't state.
